spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:pagamentodb
    username: sa
    password:
    driverClassName: org.h2.Driver
server:
  port: 8089
springdoc:
  swagger-ui:
    path: /swagger-ui/index.html
    operations-sorter: method